# --- entrenador ---
ENERGIA_CREAR_OBJETO = 15 # GASTA UN 15% DE SU ENERGIA
PROB_EXITO_OBJETO = 0.7
ENERGIA_ENTRENAMIENTO = 12
# --- tipos de objetos --- 
GASTO_ENERGIA_BAYA = 10
PROB_EXITO_BAYA = 0.4 # SEGUN EL TOTAL DE OBJETOS
GASTO_ENERGIA_POCION = 15 
PROB_EXITO_POCION = 0.3  # SEGUN EL TOTAL DE OBJETOS
GASTO_ENERGIA_CARAMELO = 15
PROB_EXITO_CARAMELO = 0.3 # GASTA UN 25% DE SU ENERGIA
AUMENTO_DEFENSA = 16

# --- programon ---
MIN_AUMENTO_EXPERIENCIA = 10
MAX_AUMENTO_EXPERIENCIA = 50
MIN_AUMENTO_ENTRENAMIENTO = 25
MAX_AUMENTO_ENTRENAMIENTO = 50
AUMENTAR_VIDA_PLANTA = 77 # 30% DEL MAXIMO DE VIDA
AUMENTAR_ATAQUE_FUEGO =  57 # 30% DEL MAXIMO DE ATAQUE
AUMENTAR_VELOCIDAD_AGUA = 60 # 30% DEL MAXIMO DE VELOCIDAD

